# Generated by Django 4.2 on 2023-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='death_rate',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='local_names',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='number_affected_in_herd',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='other_livestock_affected',
            field=models.CharField(max_length=600),
        ),
    ]
